import NavTMDB from "./layout/nav";
import Header from "./layout/header";
import Movies from "./layout/movies";
import MovieCard from "./layout/movieCard";
import GenreButton from "./layout/genreButton";
import Trailer from "./layout/movieDetails/trailer";
import CastCard from "./layout/movieDetails/castCard";
import MovieCast from "./layout/movieDetails/movieCast";
import UserVotes from "./layout/movieDetails/userVotes";
import MovieHeader from "./layout/movieDetails/movieHeader";
import Recommendations from "./layout/movieDetails/recommendations";

export { NavTMDB as Nav };
export { Header };
export { GenreButton };
export { MovieHeader };
export { MovieCard };
export { MovieCast };
export { Movies };
export { UserVotes };
export { CastCard };
export { Trailer };
export { Recommendations };
